package vn.dating.app.social.dto;

public enum ResponseMessage {
    CREATED,
    CANNOT_CREATED,
    SUCCESSFUL,
    UNSUCCESSFUL,
    NOT_MEMBER,
    NOT_WORKING,
    PENDING,
    BLOCK,
    IS_MEMBER_ONLY_COMMENT,
    NOT_A_MEMBER,
    NOT_MEMBER_PRIVATE_COMMUNITY,
    PUBLIC_COMMUNITY_ONLY_VIEW,
    IS_ADMIN_COMMUNITY,
    WAITING_POST,
    PENDING_POST,

    PRIVATE,
    PUBLIC,
    WANTING,
    DELETED,
    IS_MEMBER,
    EXISTS,
    NOT_FOUND
}
